##########################################################################################################################################
# This Python script loads a python file containing the chemical network equations.
# The filename of the equations file must be given as console argument e.g. 'python3 CTOT.py Equations.py'
# The script used SymPy's symbolic algebra package to compute the derivatives of the cost function.
# Every parameter must be defined as sympy symbol
# The script uses SymPy's common subexpression elimination (CSE) technique to simplify the equations and derivatives for an optimized code
# At the end, it generates a C++ code, that can be compiled.

#Date: February 2025
#Author: Simon Grimm
##########################################################################################################################################


import sympy as sy
from sympy import log, exp, ccode
import importlib
import sys
import os


#check if Equation.py file name is given as console argument

if(len(sys.argv) <= 1):
	print("Error, Equations.py file name not given as console argument. Use python3 CTOT.py <name of Equations file>.")
	exit()

file = sys.argv[1]


#filename of the Equations.py file 
filename = file.split(".py")[0]


#check if Equations.py file exists
if(os.path.isfile(file) == False):
	print("Error, file %s does not exist." % file)
	exit()

#import Equations file with the name given as console argument
Equations = importlib.import_module(filename)




print("Using chemical network equations from file %s.py" % filename)
print("")



Equations.printff()

ff, P, variables, Parameters, nGRT  = Equations.getff()


nF = len(ff)

var = sy.IndexedBase('var', (nF,), real=True)
logvar = sy.IndexedBase('logvar', (nF,), real=True)     #This is a helper array to speed up the calculations



# ************************************************************
# Define the cost function CTOT and its gradients
# The cost function is the sum of the squares of all equations
# ************************************************************
#square of functions
ff2 = []
for f in ff:
        ff2.append(f**2)


# Costfunction
CTOT = sum(ff2)
# ************************************************************


# ***************************************************************
# Calculate the gradients of CTOT with respect to all variables
# We solve the equations in log space, therefore we need the
# derivatives in repect of the log of the variables

# df/d(log(x)) = df/dx * dx/d log(x) = df/dx * x
# ***************************************************************

print("Calculating symbolic derivatives")
useLog = 1		#0: calcualte the derivatives in respect of the values, 1: in respect of the log of the values

if(useLog == 1):
	CTOT_grad = [sy.diff(CTOT, var[i]) * var[i] for i in range(nF)] #the '*var[i]' is the inner derivative of the logarithm
else:
	CTOT_grad = [sy.diff(CTOT, var[i]) for i in range(nF)]

# ***************************************************************






#replace log(var) with the variables logvar before printing, this will speed up the calculations
for i in range(nF):
	ff[i] = ff[i].subs((log(var[i]), logvar[i]) for i in range(nF))
	#print(ccode(ff[i]))
	#print("")

for i in range(nF):
	CTOT_grad[i] = CTOT_grad[i].subs((log(var[i]), logvar[i]) for i in range(nF))

	#print(CTOT_grad[i])
	#print("")



# *********************************************************************************
# Now gnerate the c++ code of the costfunstion and the derivatives
# *********************************************************************************




# *********************************************************************************
# generate ctot.cpp file
# *********************************************************************************
filename1 = 'ctot.cpp'
file1 = open(filename1, 'w')

print('//This file is automatically generated by the python3 script CTOT.py', file = file1)
print('//This code is generated with SymPy and is using Common Subexpression Elimination (CSE) to speed up the code', file = file1)
print('', file = file1)

print('#include "../src/solver.h"', file = file1)
print('double solver::ctot(double *var, double *logvar, double P){', file = file1)
print('', file = file1)

print('\tdouble f[%d];' % nF, file = file1)
print('', file = file1)

#Use SymPy common subexpression elimination to optimize the cost function code
commons, exprs = sy.cse((ff))

names = []
for i in range(nF):
	names.append("f[%d]" % i)

print("\t//common expressions:", file = file1)

for com in commons:
	print('\tdouble ',ccode(com[0]), ' = ', ccode(com[1]), ';', sep='', file = file1)

print("", file = file1)

print("\t//reduced expressions:", file = file1)
for expr, name in zip(exprs, names):
	print('\t', name, ' = ', ccode(expr), ';', sep='', file = file1)


print("", file = file1)
print("", file = file1)
print("\t//Square all f and add them up", file = file1)
print("\tdouble CTOT = 0.0;", file = file1)
print("\tfor(int i = 0; i < Ndim; ++i){", file = file1)
print("\t\tCTOT += f[i] * f[i];", file = file1)
print("\t}", file = file1)
print("", file = file1)
print("", file = file1)
print('\treturn CTOT;', file = file1)
print('}', file = file1)

file1.close()
print("generated %s file" % filename1)
# *********************************************************************************






# *********************************************************************************
# generate grad_ctot.cpp file
# *********************************************************************************
filename2 = 'grad_ctot.cpp'
file2 = open(filename2, 'w')

print('//This file is automatically generated by the python3 script CTOT.py', file = file2)
print('//This code is generated with SymPy and is using Common Subexpression Elimination (CSE) to speed up the code', file = file2)
print('//The derivatives of the cost function are calculated automatically by using symbolic algebra from SymPy', file = file2)
print("", file = file2)

print('#include "../src/solver.h"', file = file2)
print('void solver::grad_ctot(double *var, double *logvar, double P, double *ctot_grad){', file = file2)
print("", file = file2)

names = []
for i in range(nF):
	names.append("ctot_grad[%d]" %i)


commons, exprs = sy.cse(CTOT_grad)
print("\t//common expressions:", file = file2)

for com in commons:
	print('\tdouble ',ccode(com[0]), ' = ', ccode(com[1]), ';', sep='', file = file2)
print("", file = file2)

names = []
for i in range(nF):
	names.append("ctot_grad[%d]" %i)


print("\t//reduced expressions:", file = file2)
for expr, name in zip(exprs, names):
	print('\t', name, ' = ', ccode(expr), ';', sep='', file = file2)



'''
for expr, name in zip(CTOT_grad, names):
        print('\t', name, ' = ', ccode(expr), ';', sep='')
        print('')
'''
print('}', file = file2)

file2.close()
print("generated %s file" % filename2)
# *****************************************************************************




# *********************************************************************************
# generate parameters.h file
# *********************************************************************************
filename3 = 'parameters.h'
file3 = open(filename3, 'w')

print('//This file is automatically generated by the python3 script CTOT.py', file = file3)
print("",file=file3)
print("\tconst int useLog = %d;" % useLog, file=file3)
print("\tconst int Ndim = %d; //Dimensionality of the problem" % len(ff), file=file3)
print("\tconst int nGRT = %d;" % nGRT, file=file3)
print("\tconst int nParameters = %d;" % len(Parameters), file=file3)
print("", file=file3)
print("\tstd::string ParameterNames[%d] = {" % len(Parameters), file=file3)

for i in range(len(Parameters)):
	if i < len(Parameters) - 1:
		print('\t\t"%s",' % Parameters[i], file=file3)
	else:
		print('\t\t"%s"' % Parameters[i], file=file3)
print("\t};", file=file3)
print("", file=file3)
print("", file=file3)
print("\tdouble Parameters[%d];" % len(Parameters), file=file3)

for i in range(len(Parameters)):
	print("\tdouble &%s = Parameters[%d];" % (Parameters[i], i), file=file3)

print("", file=file3)
print("", file=file3)

print("\tstd::string VariableNames[%d] = {" % len(variables), file=file3)

for i in range(len(variables)):
	if i < len(variables) - 1:
		print('\t\t"%s",' % variables[i], file=file3)
	else:
		print('\t\t"%s"' % variables[i], file=file3)
print("\t};", file=file3)

file3.close()
print("generated %s file" % filename3)
# *****************************************************************************


# *********************************************************************************
# generate calculate_P.cpp file
# *********************************************************************************
filename4 = 'calculate_P.cpp'
file4 = open(filename4, 'w')

print('//This file is automatically generated by the python3 script CTOT.py', file = file4)
print('//This code is generated with SymPy and is using Common Subexpression Elimination (CSE) to speed up the code', file = file4)
print('//Estimate atmospheric pressure at the surface of the planet', file = file4)
print("", file = file4)

print('#include "../src/solver.h"', file = file4)
print('double solver::calculate_P(double *var){', file = file4)
print("", file = file4)


commons, exprs = sy.cse(P)
print("\t//common expressions:", file = file4)

for com in commons:
        print('\tdouble ',ccode(com[0]), ' = ', ccode(com[1]), ';', sep='', file = file4)
print("", file=file4)

for expr in exprs:
	print('\tdouble P = ',ccode(expr), ';\t // in bar', sep='', file = file4)

#print('\tdouble P = ',ccode(P), ';\t // in bar', sep='', file = file4)

print("", file=file4)
print('\treturn P;', file = file4)

print('}', file = file4)

file4.close()
print("generated %s file" % filename4)

